using System.Collections.Immutable;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace Xunit.v3.IntegrationTesting.Analyzers.Generators.Tests;

public class CollectionDefinitionGeneratorTests
{
    [Fact]
    public async Task GenerateCollectionDefinitionAsync()
    {
        var source = /* lang=c#-test */ @"
            using System;
            using Xunit;
            using Xunit.v3.IntegrationTesting;

            namespace MyNamespace;

            [DependsOnClasses(Dependencies = [typeof(MyTestClass2), typeof(MyTestClass3)], Name = ""MyTestClass1_Collection"")]
            public class MyTestClass1;

            public class MyTestClass2;
            public class MyTestClass3;
        ";

        var generatedCode = /* lang=c#-test */ """
// <auto-generated/>
using System;

/// <summary>
/// Auto-generated collection definition for <see cref="MyTestClass1"/>.
/// </summary>
[Xunit.CollectionDefinition("MyTestClass1_Collection", DisableParallelization = true)]
[Xunit.v3.IntegrationTesting.DependsOnCollections(typeof(MyNamespace.MyTestClass2), typeof(MyNamespace.MyTestClass3))]
public sealed class Generated_CollectionDefinition_MyTestClass1;
""";

        var generator = GetSourceGenerator(source, generatedCode);

        await generator.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task GenerateCollectionDefinition_NoDependencies_Async()
    {
        var source = /* lang=c#-test */ @"
            using System;
            using Xunit;
            using Xunit.v3.IntegrationTesting;

            namespace MyNamespace;

            [DependsOnClasses(Name = ""MyTestClass1_Collection"")]
            public class MyTestClass1;

            public class MyTestClass2;
            public class MyTestClass3;
        ";

        var generatedCode = /* lang=c#-test */ """
// <auto-generated/>
using System;

/// <summary>
/// Auto-generated collection definition for <see cref="MyTestClass1"/>.
/// </summary>
[Xunit.CollectionDefinition("MyTestClass1_Collection", DisableParallelization = true)]
[Xunit.v3.IntegrationTesting.DependsOnCollections()]
public sealed class Generated_CollectionDefinition_MyTestClass1;
""";

        var generator = GetSourceGenerator(source, generatedCode);

        await generator.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task GenerateCollectionDefinition_MultipleClasses_Async()
    {
        var source = /* lang=c#-test */ @"
            using System;
            using Xunit;
            using Xunit.v3.IntegrationTesting;

            namespace MyNamespace;

            [DependsOnClasses(Dependencies = [typeof(MyTestClass2)], Name = ""Collection_A"")]
            public class MyTestClass1;

            [DependsOnClasses(Dependencies = [typeof(MyTestClass3)], Name = ""Collection_B"")]
            public class MyTestClass2;

            public class MyTestClass3;
        ";

        var generatedCode = /* lang=c#-test */ """
// <auto-generated/>
using System;

/// <summary>
/// Auto-generated collection definition for <see cref="MyTestClass1"/>.
/// </summary>
[Xunit.CollectionDefinition("Collection_A", DisableParallelization = true)]
[Xunit.v3.IntegrationTesting.DependsOnCollections(typeof(MyNamespace.MyTestClass2))]
public sealed class Generated_CollectionDefinition_MyTestClass1;
/// <summary>
/// Auto-generated collection definition for <see cref="MyTestClass2"/>.
/// </summary>
[Xunit.CollectionDefinition("Collection_B", DisableParallelization = true)]
[Xunit.v3.IntegrationTesting.DependsOnCollections(typeof(MyNamespace.MyTestClass3))]
public sealed class Generated_CollectionDefinition_MyTestClass2;
""";

        var generator = GetSourceGenerator(source, generatedCode);

        await generator.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task GenerateCollectionDefinition_EmptyName_NoOutput_Async()
    {
        var source = /* lang=c#-test */ @"
            using System;
            using Xunit;
            using Xunit.v3.IntegrationTesting;

            namespace MyNamespace;

            [DependsOnClasses(Dependencies = [typeof(MyTestClass2)], Name = """")]
            public class MyTestClass1;

            public class MyTestClass2;
        ";

        var generator = new CSharpSourceGeneratorTest<CollectionDefinitionGenerator, DefaultVerifier>
        {
            TestState =
            {
                Sources = { source },
                AdditionalReferences = { typeof(FactDependsOnAttribute).Assembly }
            },
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90.AddPackages(new PackageIdentity[]
            {
                new PackageIdentity("xunit.v3", "3.0.0")
            }.ToImmutableArray()),
        };

        await generator.RunAsync(TestContext.Current.CancellationToken);
    }


    private static SourceGeneratorTest<DefaultVerifier> GetSourceGenerator(string source, string generatedCode) => new CSharpSourceGeneratorTest<CollectionDefinitionGenerator, DefaultVerifier>
    {
        TestState =
        {
            Sources = { source },
            GeneratedSources =
            {
                (typeof(CollectionDefinitionGenerator), "CollectionDefinitions.g.cs", generatedCode)
            },
            AdditionalReferences = { typeof(FactDependsOnAttribute).Assembly }
        },
        ReferenceAssemblies = ReferenceAssemblies.Net.Net90.AddPackages(new PackageIdentity[]
        {
            new PackageIdentity("xunit.v3", "3.0.0")
        }.ToImmutableArray()),
    };
}