namespace Xunit.v3.IntegrationTesting;

/// <summary>
/// Used as a token to generate corresponding collection definition for test classes that have dependencies on other test classes.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public class DependsOnClassesAttribute : Attribute, ICollectionAttribute
{
    /// <summary>
    /// Gets the list of dependent classes for the test.
    /// </summary>
    public required Type[] Dependencies { get; init; }

    /// <inheritdoc />
    public required string Name { get; init; }

    /// <inheritdoc />
    /// <remarks>This property always returns <see langword="null"/>, because collection definition type will be generated by the source generator, so it can't be referenced by a type</remarks>
    public Type? Type => null;
}