
name: Build and Test - CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  # Allow manually triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write # Required to push NuGet packages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Git Versioning requires a non-shallow clone

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore -bl:logs/restore.binlog

      - name: Build
        run: dotnet build --configuration Release --no-restore -bl:logs/build.binlog

      - name: Test
        run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults --filter "Category!~LocalOnly"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults
        if: ${{ always() }} # Always run this step even on failure

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs
        if: ${{ always() }} # Always run this step even on failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./artifacts
        if: ${{ always() }} # Always run this step even on failure

      - name: Push NuGet package
        run: dotnet nuget push artifacts\*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        if: startsWith(github.ref, 'refs/tags/v')
